### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by akastrin** [GenLouvain/GenLouvain#1]
This is not directly an issue but more a question. I'm using your code to find community structures in my temporal network. Now I try to perform visualization of the communities in time. Looking at the wonderful figure in [Mucha et al. (2010)](http://www.sciencemag.org/cgi/rapidpdf/328/5980/876?ijkey=b8DfvjEigOMVc&keytype=ref&siteid=sci) (Figure 3), I wonder how to perform such visualization. Any pointer would be greatly appreciated.

**Comment by LJeub** [comment]
I suggest you have a look at the `sort_ordinal` function in the `HelperFunctions` directory. It tries to find a permutation of the nodes that emphasizes persistent community structure. 

For a quick approximation to the figure try

```
[Ssorted, s]=sort_ordinal(ST)
imagesc(Ssorted)
```

where `ST=reshape(S,N,T)` is the reshaped output partition where each column gives the identified communities for a time window. From there you can play with the style of the figure.
