### ISSUE TITLE
Modularity in iterated_genlouvain appear random (multilayer network)  

### ISSUE THREAD

**Issue by ismailukman** [GenLouvain/GenLouvain#10]
`[S_g1, Q_g1] = iterated_genlouvain(B_g1,10000,0,1,'moverandw',[], PP_g1); `

Output values of S_g1 were observed to have some element of randomness i.e for a give input data over successive independent execution, outputs are not the same, how can this randomness be removed?
I have tried switching from `moverandw` to `move` but no significant improvement.

Thanks in advance for your clarification/suggestion

**Comment by LJeub** [comment]
There are two sources of randomness in the genlouvain algorithm that change the result. The first is the order in which the nodes are traversed which is randomly sampled by default. The second is the choice of which modularity-increasing move to pick at each update. For fully deterministic results, you need to call it with 

```
[S_g1, Q_g1] = iterated_genlouvain(B_g1, 10000, 0, 0, 'move', [], PP_g1);
```

This can be useful for testing. In general however it is important to make sure none of your conclusions depend on a particular partition (there are no guarantees that this algorithm will find an optimal partition).

**Comment by ismailukman** [comment]
Thanks, this is helpful
