### ISSUE TITLE
Support for Multi-layered network with cross node couplings

### ISSUE THREAD

**Issue by thechargedneutron** [GenLouvain/GenLouvain#2]
Does this implementation support a network where cross connections between nodes across layers exist? (Example connections like **Node1 of Layer1 connected to Node 2 of Layer2**) . Although the formula for Modularity does not support this but is there  a way around?
I want to do community detection on such a network (basically a fully connected network). Any suggestions on how to achieve this if not supported by this package?

**Comment by LJeub** [comment]
While the package does not currently provide a function to do this out of the box, it would be almost trivial to implement on top of `genlouvain`, given that it supports a general symmetric matrix as input and is agnostic to any particular functional form for the Modularity. All that one needs to do to support such a situation is construct an appropriate modularity matrix. However, exactly how such a matrix should look depends on the meaning of your connections between layers. In any case, the modularity matrix should have a block structure, where diagonal blocks are the modularity matrices for each layer. If your connections between layers are similar to the identity connections of standard multilayer modularity (see e.g. `multiord` and `multicat`) you could implement the modularity matrix by using `modularity` to compute the modularity matrix for each layer and use the build-in `blkdiag` function to turn them into a block-diagonal matrix. Then you would simply add the cross-layer connections using a fixed weight. However, in other cases it may be necessary to include an appropriate null-model for the cross-layer connections as well (in particular if they are not identity connections and you thus don't necessarily want to incentivise nodes that are connected across layers to appear in the same community).
