### ISSUE TITLE
octave use

### ISSUE THREAD

**Issue by mb3152** [GenLouvain/GenLouvain#4]
I am having trouble compiling the MEX files for octave. I know this is probably an octave problem, but I am curious if anyone has had this issue before. Here is the command and output. Thanks! 

octave bertolem/GenLouvain-master/MEX_SRC/compile_mex.m
warning: docstring file '/usr/share/octave/3.8.2/etc/built-in-docstrings' not found
GNU Octave, version 3.8.2
Copyright (C) 2014 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-redhat-linux-gnu".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/get-involved.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

warning: unknown mexext mex, assuming 64bit
error: mkoctfile: unable to find the mkoctfile command, Octave installation is incomplete

**Comment by LJeub** [comment]
As you suspect there seems to be a problem with your Octave installation. Octave is unable to find the `mkoctfile` function which is responsible for compiling .mex files. You may want to try reinstalling Octave. 

The warning before that is generated by our code and you can safely ignore it as your system appears to be 64bit.

**Comment by mb3152** [comment]
Thanks! I had our cluster manager reinstall Octave and that worked. I did get some warnings, though. The code seems to return very similar results across matlab.engine and octave, though. I don't know any MATLAB syntax, so I just wanted to make sure these warnings were okay. Thanks again for your time. 

(base) [bertolem@cubic-login4 MEX_SRC]$ octave compile_mex.m 
warning: docstring file '/usr/share/octave/3.8.2/etc/built-in-docstrings' not found
GNU Octave, version 3.8.2
Copyright (C) 2014 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-redhat-linux-gnu".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/get-involved.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

warning: unknown mexext mex, assuming 64bit
metanetwork_reduce.cpp: In function ‘void mexFunction(int, mxArray**, int, const mxArray**)’:
metanetwork_reduce.cpp:129:29: warning: suggest parentheses around comparison in operand of ‘|’ [-Wparentheses]
                     if (nrhs!=1|nlhs!=1) {
                             ^
In file included from matlab_matrix/full.cpp:14:0:
matlab_matrix/matlab_matrix.h: In constructor ‘full::full()’:
matlab_matrix/matlab_matrix.h:110:9: warning: ‘full::n’ will be initialized after [-Wreorder]
  mwSize n;
         ^
matlab_matrix/matlab_matrix.h:109:9: warning:   ‘mwSize full::m’ [-Wreorder]
  mwSize m;
         ^
matlab_matrix/full.cpp:17:1: warning:   when initialized here [-Wreorder]
 full::full(): n(0), m(0), val(NULL), export_flag(0) {}
 ^
In file included from matlab_matrix/full.cpp:14:0:
matlab_matrix/matlab_matrix.h: In constructor ‘full::full()’:
matlab_matrix/matlab_matrix.h:110:9: warning: ‘full::n’ will be initialized after [-Wreorder]
  mwSize n;
         ^
matlab_matrix/matlab_matrix.h:109:9: warning:   ‘mwSize full::m’ [-Wreorder]
  mwSize m;
         ^
matlab_matrix/full.cpp:17:1: warning:   when initialized here [-Wreorder]
 full::full(): n(0), m(0), val(NULL), export_flag(0) {}
 ^

**Comment by LJeub** [comment]
These warnings are generated by the C++ compiler. The warning is generated because the constructor for full is initialising the member variables `n` and `m` in a way that is inconsistent with the order in which they were defined. They are both initialised to 0 so this does not cause any problems in this case.
