### ISSUE TITLE
Bug? Comparison between double and string is not supported

### ISSUE THREAD

**Issue by giovannetti87** [GenLouvain/GenLouvain#8]
Dear GenLouvain team,

I apologize if this is not a bug but rather due to my incompetence. In which case I will be happy to close it asap.  I am trying to run your script on a sparse network matrix but after a few iteration the script returns the error enclosed down below.

The code I am running is as follows:

N = table of Node features (including column "Name")
D = table of Edge features (including the column "EndNodes")

network = digraph(D, N);

n = numel(network.Nodes.Name);

adj_net = sparse(n,n)  +  adjacency(network );  % this way, we obtain a nxn matrix filled with either zero or ones
 
[B,twom] = modularitydir_f(adj_net ,1);

lou = genlouvain(B,verbose=1);
 

The code produces the following:

Merging 364108 communities  03-Nov-2023 12:09:42
361986 change: 3135.6397 total: 3135.6397 relative: 1
361963 change: 47.3485 total: 3182.9881 relative: 0.014875
361960 change: 5.4692 total: 3188.4574 relative: 0.0017153
361960 change: 2.9646 total: 3191.422 relative: 0.00092894
361959 change: 1.9864 total: 3193.4083 relative: 0.00062202
361959 change: 0 total: 3193.4083 relative: 0
Error using  > 
Comparison between double and string is not supported.

Error in genlouvain (line 304)
    if (t>limit)

Error in iterated_genlouvain (line 215)
[S,Q]=genlouvain(B,limit,verbose,randord,randmove,S0);

Thank you for the massive work. This suite is definitely superior to any other Louven algorithm I could find online, and very advanced for my skills. I am learning a lot about (the right way to program in) Matlab thanks to you.

**Comment by LJeub** [comment]
I don't have access to Matlab right now to test this but I think I know what is happening. This code is pretty old and was written before the `name=value` syntax existed and has no support for specifying non-default values in this way. What seems to happen is that internally Matlab parses `name=value` as two arguments where the first one is the string `"name"` and the second one is the `value`. 

As a result the `limit` parameter is set to the string `"verbose"` which then results in the comparison error.  The arguments are strictly positional only but `verbose=1` is already default so you can just use `genlouvain(B)` (you can also keep the default value by specifying an empty value for the argument like this `genlouvain(B, [], 1)`.

**Comment by giovannetti87** [comment]
Hi @LJeub, thanks for taking this so promptly. I am sorry I did not reply earlier but I wanted to actually run the code



I think you are right relative to the error. By running:

[B,twom] = modularitydir_f(adj_coop_net_acc,1);
tic
lou = genlouvain(B);
toc

The algorithm goes through:

Merging 364108 communities  04-Nov-2023 12:03:54
361997 change: 3130.1638 total: 3130.1638 relative: 1
361963 change: 54.8058 total: 3184.9697 relative: 0.017208
361960 change: 2.4871 total: 3187.4567 relative: 0.00078026
361960 change: 0 total: 3187.4567 relative: 0
Merging 361960 communities  04-Nov-2023 12:38:42
361948 change: 26.794 total: 3214.2508 relative: 0.008336
361948 change: 0 total: 3214.2508 relative: 0
Merging 361948 communities  04-Nov-2023 13:44:30
361948 change: 0 total: 3214.2508 relative: 0
Elapsed time is 9590.021973 seconds.


However, it looks like the resulting communities are exactly coincident with the components. Is that because of the parameter? 

Thanks a lot
andrea

**Comment by LJeub** [comment]
Yes, this is not unexpected. If your network has many components it is likely that they correspond to a high (maybe even maximum) modularity partition. You can try to increase the gamma parameter to try to encourage the algorithm to split components further. Alternatively you could also try to find communities within the components by running the algorithm separately on each (or maybe only the largest component if it is most of your network). By design, any modularity-based algorithm should not place nodes from different components into the same community.
