### ISSUE TITLE
The link for more documentation does not work

### ISSUE THREAD

**Issue by jesmaelpoor** [GenLouvain/GenLouvain#9]
Dear Lucas,

The followings link does not work anymore: http://netwiki.amath.unc.edu/GenLouvain
Where can I find the documentations?

Thank you very much.

Jamal Esmaelpoor.

**Comment by LJeub** [comment]
If you are curious you can still find it on the internet archive: https://web.archive.org/web/20220323035538/http://netwiki.amath.unc.edu/GenLouvain/GenLouvain

However, while those examples should still work, there are now prebuilt functions for those scenarios (have a look at `doc('HelperFunctions')` for a list. In general, all the functions have fairly extensive documentation comments which should hopefully get you started. I have updated the readme to remove the broken link and point to the inline documentation instead.

**Comment by jesmaelpoor** [comment]
Hi Lucas,

Thank you very much for providing me with the link.

*Best Regards,*
*Jamal Esmaelpoor,*
*Phone: +61411490080.*
